# Generated by Django 4.1.2 on 2022-10-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
