repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings
        exclude: migrations/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        additional_dependencies:
          - django
          - django-stubs
          - djangorestframework
          - djangorestframework-stubs
          - python-dotenv
        exclude: migrations/
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.26.0
    hooks:
      - id: eslint
        files: ^frontend/
        types_or: [ts, tsx]
        types: [file]
        additional_dependencies:
          - eslint-plugin-react
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: ^frontend/
        types_or: [ts, tsx]
        types: [file]
