# Generated by Django 4.1.3 on 2022-11-16 22:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cognito", "0002_alter_cognitouser_options_cognitouser_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cognitouser",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
