# Generated by Django 4.1.3 on 2022-11-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cognito", "0003_alter_cognitouser_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cognitouser",
            name="password",
        ),
    ]
