# Generated by Django 4.1.3 on 2022-11-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cognito", "0006_alter_cognitouser_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="cognitouser",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
