# Generated by Django 4.1.3 on 2022-11-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cognito", "0007_cognitouser_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="cognitouser",
            name="password",
            field=models.CharField(default="", max_length=128, verbose_name="password"),
            preserve_default=False,
        ),
    ]
